/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SafeBaseV3 {
  export type DealStruct = {
    payer: AddressLike;
    payee: AddressLike;
    amount: BigNumberish;
    deadline: BigNumberish;
    hashlock: BytesLike;
    status: BigNumberish;
    tokenType: BigNumberish;
    token: AddressLike;
    createdAt: BigNumberish;
  };

  export type DealStructOutput = [
    payer: string,
    payee: string,
    amount: bigint,
    deadline: bigint,
    hashlock: string,
    status: bigint,
    tokenType: bigint,
    token: string,
    createdAt: bigint
  ] & {
    payer: string;
    payee: string;
    amount: bigint;
    deadline: bigint;
    hashlock: string;
    status: bigint;
    tokenType: bigint;
    token: string;
    createdAt: bigint;
  };
}

export interface SafeBaseV3Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE_DENOMINATOR"
      | "MAX_FEE_RATE"
      | "UPGRADE_INTERFACE_VERSION"
      | "collectedFees"
      | "createDealERC20"
      | "createDealETH"
      | "disputeDeal"
      | "feeRate"
      | "getDeal"
      | "getUserDeals"
      | "getValue"
      | "initialize"
      | "initializeV3"
      | "owner"
      | "proxiableUUID"
      | "refund"
      | "renounceOwnership"
      | "resolveByOwner"
      | "reveal"
      | "setFeeRate"
      | "setValue"
      | "totalFeesCollected"
      | "transferOwnership"
      | "upgradeToAndCall"
      | "userDealCount"
      | "userDeals"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DealCreated"
      | "DealDisputed"
      | "DealRefunded"
      | "DealResolved"
      | "DealRevealed"
      | "FeeCollected"
      | "FeeRateUpdated"
      | "FeesWithdrawn"
      | "Initialized"
      | "OwnershipTransferred"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FEE_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_FEE_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collectedFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createDealERC20",
    values: [
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createDealETH",
    values: [BytesLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeDeal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "feeRate", values?: undefined): string;
  encodeFunctionData(functionFragment: "getDeal", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getUserDeals",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getValue", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeV3",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "refund", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveByOwner",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reveal",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalFeesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userDealCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userDeals",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "FEE_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_FEE_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDealERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDealETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeDeal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeRate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDeal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserDeals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getValue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeV3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reveal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFeeRate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setValue", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userDealCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userDeals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace DealCreatedEvent {
  export type InputTuple = [
    dealId: BytesLike,
    payer: AddressLike,
    payee: AddressLike,
    amount: BigNumberish,
    deadline: BigNumberish,
    hashlock: BytesLike,
    tokenType: BigNumberish,
    token: AddressLike
  ];
  export type OutputTuple = [
    dealId: string,
    payer: string,
    payee: string,
    amount: bigint,
    deadline: bigint,
    hashlock: string,
    tokenType: bigint,
    token: string
  ];
  export interface OutputObject {
    dealId: string;
    payer: string;
    payee: string;
    amount: bigint;
    deadline: bigint;
    hashlock: string;
    tokenType: bigint;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealDisputedEvent {
  export type InputTuple = [dealId: BytesLike, disputer: AddressLike];
  export type OutputTuple = [dealId: string, disputer: string];
  export interface OutputObject {
    dealId: string;
    disputer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealRefundedEvent {
  export type InputTuple = [
    dealId: BytesLike,
    payer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [dealId: string, payer: string, amount: bigint];
  export interface OutputObject {
    dealId: string;
    payer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealResolvedEvent {
  export type InputTuple = [
    dealId: BytesLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [dealId: string, to: string, amount: bigint];
  export interface OutputObject {
    dealId: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealRevealedEvent {
  export type InputTuple = [
    dealId: BytesLike,
    payee: AddressLike,
    amount: BigNumberish,
    secret: BytesLike
  ];
  export type OutputTuple = [
    dealId: string,
    payee: string,
    amount: bigint,
    secret: string
  ];
  export interface OutputObject {
    dealId: string;
    payee: string;
    amount: bigint;
    secret: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeCollectedEvent {
  export type InputTuple = [dealId: BytesLike, feeAmount: BigNumberish];
  export type OutputTuple = [dealId: string, feeAmount: bigint];
  export interface OutputObject {
    dealId: string;
    feeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeRateUpdatedEvent {
  export type InputTuple = [oldRate: BigNumberish, newRate: BigNumberish];
  export type OutputTuple = [oldRate: bigint, newRate: bigint];
  export interface OutputObject {
    oldRate: bigint;
    newRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesWithdrawnEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SafeBaseV3 extends BaseContract {
  connect(runner?: ContractRunner | null): SafeBaseV3;
  waitForDeployment(): Promise<this>;

  interface: SafeBaseV3Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  MAX_FEE_RATE: TypedContractMethod<[], [bigint], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  collectedFees: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  createDealERC20: TypedContractMethod<
    [
      dealId: BytesLike,
      payee: AddressLike,
      amount: BigNumberish,
      deadline: BigNumberish,
      hashlock: BytesLike,
      token: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  createDealETH: TypedContractMethod<
    [
      dealId: BytesLike,
      payee: AddressLike,
      deadline: BigNumberish,
      hashlock: BytesLike
    ],
    [void],
    "payable"
  >;

  disputeDeal: TypedContractMethod<[dealId: BytesLike], [void], "nonpayable">;

  feeRate: TypedContractMethod<[], [bigint], "view">;

  getDeal: TypedContractMethod<
    [dealId: BytesLike],
    [SafeBaseV3.DealStructOutput],
    "view"
  >;

  getUserDeals: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  getValue: TypedContractMethod<[], [bigint], "view">;

  initialize: TypedContractMethod<
    [initialValue: BigNumberish, owner_: AddressLike],
    [void],
    "nonpayable"
  >;

  initializeV3: TypedContractMethod<[], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  refund: TypedContractMethod<[dealId: BytesLike], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveByOwner: TypedContractMethod<
    [dealId: BytesLike, to: AddressLike],
    [void],
    "nonpayable"
  >;

  reveal: TypedContractMethod<
    [dealId: BytesLike, secret: BytesLike],
    [void],
    "nonpayable"
  >;

  setFeeRate: TypedContractMethod<
    [newFeeRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  setValue: TypedContractMethod<[newValue: BigNumberish], [void], "nonpayable">;

  totalFeesCollected: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  userDealCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  userDeals: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  withdrawFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_FEE_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "collectedFees"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "createDealERC20"
  ): TypedContractMethod<
    [
      dealId: BytesLike,
      payee: AddressLike,
      amount: BigNumberish,
      deadline: BigNumberish,
      hashlock: BytesLike,
      token: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createDealETH"
  ): TypedContractMethod<
    [
      dealId: BytesLike,
      payee: AddressLike,
      deadline: BigNumberish,
      hashlock: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "disputeDeal"
  ): TypedContractMethod<[dealId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "feeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDeal"
  ): TypedContractMethod<
    [dealId: BytesLike],
    [SafeBaseV3.DealStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserDeals"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [initialValue: BigNumberish, owner_: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initializeV3"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[dealId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveByOwner"
  ): TypedContractMethod<
    [dealId: BytesLike, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reveal"
  ): TypedContractMethod<
    [dealId: BytesLike, secret: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFeeRate"
  ): TypedContractMethod<[newFeeRate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setValue"
  ): TypedContractMethod<[newValue: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "userDealCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userDeals"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "DealCreated"
  ): TypedContractEvent<
    DealCreatedEvent.InputTuple,
    DealCreatedEvent.OutputTuple,
    DealCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DealDisputed"
  ): TypedContractEvent<
    DealDisputedEvent.InputTuple,
    DealDisputedEvent.OutputTuple,
    DealDisputedEvent.OutputObject
  >;
  getEvent(
    key: "DealRefunded"
  ): TypedContractEvent<
    DealRefundedEvent.InputTuple,
    DealRefundedEvent.OutputTuple,
    DealRefundedEvent.OutputObject
  >;
  getEvent(
    key: "DealResolved"
  ): TypedContractEvent<
    DealResolvedEvent.InputTuple,
    DealResolvedEvent.OutputTuple,
    DealResolvedEvent.OutputObject
  >;
  getEvent(
    key: "DealRevealed"
  ): TypedContractEvent<
    DealRevealedEvent.InputTuple,
    DealRevealedEvent.OutputTuple,
    DealRevealedEvent.OutputObject
  >;
  getEvent(
    key: "FeeCollected"
  ): TypedContractEvent<
    FeeCollectedEvent.InputTuple,
    FeeCollectedEvent.OutputTuple,
    FeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "FeeRateUpdated"
  ): TypedContractEvent<
    FeeRateUpdatedEvent.InputTuple,
    FeeRateUpdatedEvent.OutputTuple,
    FeeRateUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeesWithdrawn"
  ): TypedContractEvent<
    FeesWithdrawnEvent.InputTuple,
    FeesWithdrawnEvent.OutputTuple,
    FeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "DealCreated(bytes32,address,address,uint256,uint64,bytes32,uint8,address)": TypedContractEvent<
      DealCreatedEvent.InputTuple,
      DealCreatedEvent.OutputTuple,
      DealCreatedEvent.OutputObject
    >;
    DealCreated: TypedContractEvent<
      DealCreatedEvent.InputTuple,
      DealCreatedEvent.OutputTuple,
      DealCreatedEvent.OutputObject
    >;

    "DealDisputed(bytes32,address)": TypedContractEvent<
      DealDisputedEvent.InputTuple,
      DealDisputedEvent.OutputTuple,
      DealDisputedEvent.OutputObject
    >;
    DealDisputed: TypedContractEvent<
      DealDisputedEvent.InputTuple,
      DealDisputedEvent.OutputTuple,
      DealDisputedEvent.OutputObject
    >;

    "DealRefunded(bytes32,address,uint256)": TypedContractEvent<
      DealRefundedEvent.InputTuple,
      DealRefundedEvent.OutputTuple,
      DealRefundedEvent.OutputObject
    >;
    DealRefunded: TypedContractEvent<
      DealRefundedEvent.InputTuple,
      DealRefundedEvent.OutputTuple,
      DealRefundedEvent.OutputObject
    >;

    "DealResolved(bytes32,address,uint256)": TypedContractEvent<
      DealResolvedEvent.InputTuple,
      DealResolvedEvent.OutputTuple,
      DealResolvedEvent.OutputObject
    >;
    DealResolved: TypedContractEvent<
      DealResolvedEvent.InputTuple,
      DealResolvedEvent.OutputTuple,
      DealResolvedEvent.OutputObject
    >;

    "DealRevealed(bytes32,address,uint256,bytes32)": TypedContractEvent<
      DealRevealedEvent.InputTuple,
      DealRevealedEvent.OutputTuple,
      DealRevealedEvent.OutputObject
    >;
    DealRevealed: TypedContractEvent<
      DealRevealedEvent.InputTuple,
      DealRevealedEvent.OutputTuple,
      DealRevealedEvent.OutputObject
    >;

    "FeeCollected(bytes32,uint256)": TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;
    FeeCollected: TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;

    "FeeRateUpdated(uint256,uint256)": TypedContractEvent<
      FeeRateUpdatedEvent.InputTuple,
      FeeRateUpdatedEvent.OutputTuple,
      FeeRateUpdatedEvent.OutputObject
    >;
    FeeRateUpdated: TypedContractEvent<
      FeeRateUpdatedEvent.InputTuple,
      FeeRateUpdatedEvent.OutputTuple,
      FeeRateUpdatedEvent.OutputObject
    >;

    "FeesWithdrawn(address,uint256)": TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;
    FeesWithdrawn: TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
